name: Auto Update Bus Dictionary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run JS script to fetch bus data
        run: node update_bus.js

      - name: Check file existence and commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 用 -A 自動追蹤所有新增、修改及被刪除嘅檔案
          git add -A
          
          git commit -m "Auto-update bus_dict.json [skip ci]" || echo "No changes to commit"
          git push
